services:
  server1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - SERVER_NAME=server1
  server2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - SERVER_NAME=server2
  server3:
    build: .
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
      - SERVER_NAME=server3
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2
      - server3